import request from "supertest";
import { jest } from "@jest/globals";
import app from "../src/index.js";
import { prisma } from "../src/lib/prisma.js";

// Mock Nodemailer to keep tests fast and prevent network queries
jest.unstable_mockModule("../src/utils/mailer.js", () => ({
  sendEmail: jest.fn().mockImplementation(async () => {
    return { messageId: "mock-test-message-id" };
  }),
}));

describe("INTEXIA Cyber LMS Backend API Test Suite", () => {
  let studentToken = "";
  let studentRefreshToken = "";
  let studentUserId = null;
  let adminToken = "";
  let testCourseId = null;
  let testModuleId = null;

  const testStudentEmail = "teststudent@intexia.com";
  const testAdminEmail = "testadmin@intexia.com";
  const testPassword = "securePassword123";

  // Cleanup database records generated by tests
  afterAll(async () => {
    try {
      // Delete test settings
      await prisma.setting.deleteMany({
        where: { key: "test_setting_key" }
      });
      // Delete test module resources
      await prisma.resource.deleteMany({
        where: { title: "Lecture Slides Notes" }
      });
      // Delete test users and associated relations
      await prisma.refreshToken.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.moduleCompletion.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.progress.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.enrollment.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.user.deleteMany({
        where: { email: { in: [testStudentEmail, testAdminEmail] } }
      });
    } catch (err) {
      console.error("Cleanup error:", err);
    } finally {
      await prisma.$disconnect();
    }
  });

  beforeAll(async () => {
    // Clean up any stale test records from previous failed runs to ensure a clean slate
    try {
      await prisma.setting.deleteMany({
        where: { key: "test_setting_key" }
      });
      await prisma.resource.deleteMany({
        where: { title: "Lecture Slides Notes" }
      });
      await prisma.refreshToken.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.moduleCompletion.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.progress.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.enrollment.deleteMany({
        where: { user: { email: { in: [testStudentEmail, testAdminEmail] } } }
      });
      await prisma.user.deleteMany({
        where: { email: { in: [testStudentEmail, testAdminEmail] } }
      });
    } catch (err) {
      console.error("Stale data cleanup error:", err);
    }

    // Locate or create a test course and module to verify progress endpoints
    const course = await prisma.course.findFirst({
      include: { modules: true }
    });
    if (course) {
      testCourseId = course.id;
      if (course.modules && course.modules.length > 0) {
        testModuleId = course.modules[0].id;
      }
    }
  });

  describe("1. Authentication Route Handlers", () => {
    it("should register a new student user successfully", async () => {
      const res = await request(app)
        .post("/api/auth/register")
        .send({
          name: "Test Student User",
          email: testStudentEmail,
          password: testPassword,
          mobile: "9988776655"
        });

      expect(res.status).toBe(201);
      expect(res.body).toHaveProperty("token");
      expect(res.body).toHaveProperty("refreshToken");
      expect(res.body.user).toHaveProperty("email", testStudentEmail);
      expect(res.body.user).toHaveProperty("role", "STUDENT");

      studentToken = res.body.token;
      studentRefreshToken = res.body.refreshToken;
      studentUserId = res.body.user.id;
    });

    it("should login the student and return access/refresh tokens", async () => {
      const res = await request(app)
        .post("/api/auth/login")
        .send({
          email: testStudentEmail,
          password: testPassword
        });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("token");
      expect(res.body).toHaveProperty("refreshToken");
      expect(res.body.user.email).toBe(testStudentEmail);
    });

    it("should refresh the access token and rotate the refresh token", async () => {
      const res = await request(app)
        .post("/api/auth/refresh")
        .send({
          refreshToken: studentRefreshToken
        });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("token");
      expect(res.body).toHaveProperty("refreshToken");

      // Save the rotated refresh token for future tests
      studentRefreshToken = res.body.refreshToken;
      studentToken = res.body.token;
    });

    it("should reject token refresh requests with invalid tokens", async () => {
      const res = await request(app)
        .post("/api/auth/refresh")
        .send({
          refreshToken: "invalid-mock-signature-token"
        });

      expect(res.status).toBe(401);
    });
  });

  describe("2. Student Courses Catalog & Progress API", () => {
    it("should retrieve the courses catalog listing", async () => {
      const res = await request(app)
        .get("/api/courses");

      expect(res.status).toBe(200);
      expect(Array.isArray(res.body)).toBe(true);
    });

    it("should deny course enrollment without authentication token", async () => {
      if (!testCourseId) return;

      const res = await request(app)
        .post(`/api/courses/${testCourseId}/enroll`)
        .send({});

      expect(res.status).toBe(401);
    });

    it("should enroll the student in a course", async () => {
      if (!testCourseId) return;

      const res = await request(app)
        .post(`/api/courses/${testCourseId}/enroll`)
        .set("Authorization", `Bearer ${studentToken}`);

      expect(res.status).toBe(201);
      expect(res.body).toHaveProperty("message");
    });

    it("should fetch progress of the enrolled course", async () => {
      if (!testCourseId) return;

      const res = await request(app)
        .get(`/api/courses/${testCourseId}/progress`)
        .set("Authorization", `Bearer ${studentToken}`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("completedLessons");
      expect(Array.isArray(res.body.data)).toBe(true);
    });

    it("should update and toggle module completion progress", async () => {
      if (!testCourseId || !testModuleId) return;

      const res = await request(app)
        .post(`/api/courses/${testCourseId}/progress`)
        .set("Authorization", `Bearer ${studentToken}`)
        .send({
          moduleId: testModuleId,
          completed: true
        });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("completedLessons");
      expect(res.body.data).toContain(testModuleId);
    });
  });

  describe("3. Instructor Portal API Access Control", () => {
    it("should block students from viewing instructor dashboards", async () => {
      const res = await request(app)
        .get("/api/instructor/analytics")
        .set("Authorization", `Bearer ${studentToken}`);

      expect(res.status).toBe(403); // Student doesn't have instructor authentication clearance
    });
  });

  describe("4. Administrative Dashboard Controls", () => {
    // Create an Admin user in the database directly to test admin access
    beforeAll(async () => {
      await prisma.user.create({
        data: {
          name: "Test Admin User",
          email: testAdminEmail,
          passwordHash: "dummyHash",
          role: "ADMIN"
        }
      });
      // Generate admin token
      const res = await request(app)
        .post("/api/auth/login")
        .send({
          email: testStudentEmail, // use login and then elevate or login directly
          password: testPassword
        });
      
      // Let's sign adminToken directly using the key to bypass password verification since passwordHash is placeholder
      const jwt = (await import("jsonwebtoken")).default;
      adminToken = jwt.sign(
        { id: 9999, email: testAdminEmail, role: "ADMIN" },
        process.env.JWT_SECRET || "cyber-lms-super-secret-key-change-me",
        { expiresIn: "1h" }
      );
    });

    it("should retrieve users list for admins", async () => {
      const res = await request(app)
        .get("/api/admin/users")
        .set("Authorization", `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("users");
      expect(Array.isArray(res.body.users)).toBe(true);
    });

    it("should toggle student account activation status", async () => {
      if (!studentUserId) return;

      const res = await request(app)
        .patch(`/api/admin/users/${studentUserId}/status`)
        .set("Authorization", `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("isActive");
    });
  });

  describe("5. User Profile Update & Avatar Upload", () => {
    it("should update student profile and upload avatar successfully", async () => {
      if (!studentUserId) return;

      const res = await request(app)
        .patch(`/api/users/${studentUserId}`)
        .set("Authorization", `Bearer ${studentToken}`)
        .field("name", "Updated Student Name")
        .field("mobile", "9900112233")
        .attach("avatar", Buffer.from("fake-avatar-binary-data"), "avatar.png");

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("name", "Updated Student Name");
      expect(res.body).toHaveProperty("mobile", "9900112233");
      expect(res.body).toHaveProperty("avatar");
      expect(res.body.avatar).toMatch(/^\/(uploads|lms)/);
    });

    it("should prevent updating another user profile", async () => {
      if (!studentUserId) return;

      const res = await request(app)
        .patch(`/api/users/99999`)
        .set("Authorization", `Bearer ${studentToken}`)
        .field("name", "Hacker Attempt");

      expect(res.status).toBe(403);
    });
  });

  describe("6. Course Module Lesson Resources", () => {
    it("should upload a module resource successfully", async () => {
      if (!testCourseId || !testModuleId) return;

      const res = await request(app)
        .post(`/api/courses/${testCourseId}/modules/${testModuleId}/resources`)
        .set("Authorization", `Bearer ${adminToken}`)
        .field("title", "Lecture Slides Notes")
        .field("fileType", "pdf")
        .attach("file", Buffer.from("fake-pdf-content"), "slides.pdf");

      expect(res.status).toBe(201);
      expect(res.body).toHaveProperty("id");
      expect(res.body).toHaveProperty("title", "Lecture Slides Notes");
      expect(res.body).toHaveProperty("fileType", "pdf");
      expect(res.body).toHaveProperty("fileUrl");
    });

    it("should retrieve resources for a module successfully", async () => {
      if (!testCourseId || !testModuleId) return;

      const res = await request(app)
        .get(`/api/courses/${testCourseId}/modules/${testModuleId}/resources`)
        .set("Authorization", `Bearer ${studentToken}`);

      expect(res.status).toBe(200);
      expect(Array.isArray(res.body)).toBe(true);
      expect(res.body.length).toBeGreaterThan(0);
      expect(res.body[0]).toHaveProperty("title", "Lecture Slides Notes");
    });
  });

  describe("7. Administrative Settings REST API", () => {
    it("should allow admin to create/update settings by key", async () => {
      const res = await request(app)
        .patch("/api/admin/settings/test_setting_key")
        .set("Authorization", `Bearer ${adminToken}`)
        .send({ value: "test_value" });

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("key", "test_setting_key");
      expect(res.body).toHaveProperty("value", "test_value");
    });

    it("should retrieve the list of platform settings for admins", async () => {
      const res = await request(app)
        .get("/api/admin/settings")
        .set("Authorization", `Bearer ${adminToken}`);

      expect(res.status).toBe(200);
      expect(Array.isArray(res.body)).toBe(true);
      const testSetting = res.body.find(s => s.key === "test_setting_key");
      expect(testSetting).toBeDefined();
      expect(testSetting.value).toBe("test_value");
    });
  });

  describe("8. Module Lesson Complete API Check", () => {
    it("should allow student to mark a module complete", async () => {
      if (!testCourseId || !testModuleId) return;

      const res = await request(app)
        .post(`/api/courses/${testCourseId}/modules/${testModuleId}/complete`)
        .set("Authorization", `Bearer ${studentToken}`)
        .send({});

      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("complete");
    });
  });
});
